spring.application.name=inventoryservice
server.port=8080

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/foodordering
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
