spring.application.name=auth-service
server.port=8086

keycloak.token-uri=http://localhost:8090/realms/food-security-realm/protocol/openid-connect/token
keycloak.admin-users-uri=http://localhost:8090/admin/realms/food-security-realm/users
keycloak.client-id=auth-service
keycloak.client-secret=79PnNgesetgwUf0KeUDww9DkQeQ17JGs

customer.service.url=http://localhost:8079/api/v1/customer
