spring.application.name=customerservice

server.port=8079

spring.datasource.url=jdbc:postgresql://localhost:5432/foodordering
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
